### PR TITLE
Fixing sameAs matcher

### PR DESCRIPTION
**Pull request by alemela**
I've removed the duplicated code, moving the unique part in another matcher. I've also added a loop to remove caps in the second call and to not propagate the sameAs (it could go on forever :D).

### CODE REVIEW

**Comment by retog** [comment]
Very elegant context juggling!

**Comment by alemela** [comment]
Thanks! During dbpedia fetch comes along also inverse triples and they are processed like blank nodes without being. Let me know what you think about (e.g. testing with Biel).

**Comment by retog** [comment]
I've added to `node_modules/tbbt-ld/dist/tbbt.nt`:

```
<http://localhost:8080/data/person/sheldon-cooper> <http://www.w3.org/2002/07/owl#sameAs> <https://www.w3.org/People/Berners-Lee/card#i> .
<http://localhost:8080/data/person/sheldon-cooper> <http://www.w3.org/2002/07/owl#sameAs> <http://dbpedia.org/resource/Sheldon_Cooper> .
```

Things are looking correct apart that are are several sections with `undefined` as title,e.g.

```
undefined
foaf:primaryTopic   http://dbpedia.org/resource/Sheldon_Cooper
```

**Comment by retog** [comment]
The problem described above occurs also with just one owl:sameAs and it did not occur before this PR so right now this cannot be merged.

**Comment by alemela** [comment]
Yes the problem occurs because before PR we don't navigate blank nodes during sameAs. In fact dbpedia hasn't blank nodes but inverse triple. The undefined is the subject of the triple that isn't sheldon, in the example, but something else. In the old "dbpediall" I disabled the possibilty to show these nodes, but now I try to find a better solution.

**Pull request merged**
